server {
listen 80;
charset utf-8;
# 1. 프론트엔드 (index.html 등)
location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
}

# 2. 백엔드 API 연결
location /jiwon/api/ {
    proxy_pass http://internal-zones-fastapi-internal-alb-634049921.ap-southeast-1.elb.amazonaws.com:8002/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}


}